import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  generatePropertyVaultOpenApiDocument,
  propertyVaultRouteCatalog,
} from './system.ts';

const CONTRACTS_SRC_DIR = path.dirname(fileURLToPath(import.meta.url));
const GENERATED_DIR = path.join(CONTRACTS_SRC_DIR, 'generated');
const GENERATED_OPENAPI_PATH = path.join(GENERATED_DIR, 'openapi.json');
const GENERATED_CLIENT_PATH = path.join(GENERATED_DIR, 'client.ts');
const GENERATE_COMMAND = 'npm run --workspace @dabrowskiego/contracts openapi:generate';

interface GeneratedArtifact {
  content: string;
  description: string;
  path: string;
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const checkOnly = args.includes('--check');
  const outIndex = args.indexOf('--out');
  const outPath = outIndex >= 0 ? args[outIndex + 1] : undefined;
  const document = generatePropertyVaultOpenApiDocument();
  const serializedDocument = `${JSON.stringify(document, null, 2)}\n`;

  if (checkOnly) {
    await assertArtifactsAreCurrent([
      {
        content: serializedDocument,
        description: 'Generated OpenAPI snapshot',
        path: GENERATED_OPENAPI_PATH,
      },
      {
        content: renderGeneratedClientSource(),
        description: 'Generated contract client',
        path: GENERATED_CLIENT_PATH,
      },
    ]);
    process.stdout.write('Generated contract artifacts are up to date.\n');
    return;
  }

  if (outPath) {
    const resolvedOutPath = path.resolve(process.cwd(), outPath);
    await mkdir(path.dirname(resolvedOutPath), { recursive: true });
    await writeFile(resolvedOutPath, serializedDocument, 'utf8');
    process.stdout.write(`Wrote OpenAPI document to ${resolvedOutPath}\n`);
    return;
  }

  await writeArtifacts([
    {
      content: serializedDocument,
      description: 'Generated OpenAPI snapshot',
      path: GENERATED_OPENAPI_PATH,
    },
    {
      content: renderGeneratedClientSource(),
      description: 'Generated contract client',
      path: GENERATED_CLIENT_PATH,
    },
  ]);
  process.stdout.write(`Wrote generated contract artifacts to ${GENERATED_DIR}\n`);
}

void main();

async function writeArtifacts(artifacts: readonly GeneratedArtifact[]): Promise<void> {
  await mkdir(GENERATED_DIR, { recursive: true });

  for (const artifact of artifacts) {
    await writeFile(artifact.path, artifact.content, 'utf8');
  }
}

async function assertArtifactsAreCurrent(
  artifacts: readonly GeneratedArtifact[],
): Promise<void> {
  for (const artifact of artifacts) {
    let existingContent: string;

    try {
      existingContent = await readFile(artifact.path, 'utf8');
    } catch (error) {
      const candidate = error as NodeJS.ErrnoException;

      if (candidate.code === 'ENOENT') {
        throw new Error(
          `${artifact.description} is missing at ${artifact.path}. Run \`${GENERATE_COMMAND}\`.`,
        );
      }

      throw error;
    }

    if (existingContent !== artifact.content) {
      throw new Error(
        `${artifact.description} is out of date at ${artifact.path}. Run \`${GENERATE_COMMAND}\`.`,
      );
    }
  }
}

function renderGeneratedClientSource(): string {
  const operationIds = Object.keys(propertyVaultRouteCatalog);
  const methodSignatures = operationIds
    .map(
      (operationId) => `  ${operationId}(
    ...args: ContractClientMethodArgs<PropertyVaultRouteCatalog['${operationId}']>
  ): Promise<ContractRouteSuccessResponse<PropertyVaultRouteCatalog['${operationId}']>>;`,
    )
    .join('\n');
  const methodImplementations = operationIds
    .map(
      (operationId) =>
        `    ${operationId}: buildContractClientMethod(transport, propertyVaultRouteCatalog.${operationId}),`,
    )
    .join('\n');

  return `// This file is generated by \`${GENERATE_COMMAND}\`.
// Do not edit manually.

import {
  buildContractClientMethod,
  type ContractClientMethodArgs,
  type ContractClientTransport,
  type ContractRouteSuccessResponse,
} from '../client-runtime.ts';
import { propertyVaultRouteCatalog } from '../system.ts';

type PropertyVaultRouteCatalog = typeof propertyVaultRouteCatalog;

export interface PropertyVaultContractClient {
${methodSignatures}
}

export function createPropertyVaultContractClient(
  transport: ContractClientTransport,
): PropertyVaultContractClient {
  return {
${methodImplementations}
  };
}
`;
}
